/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as LaunchRouteImport } from './routes/launch'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RoundsRouteImport } from './routes/rounds'
import { Route as StatusRouteImport } from './routes/status'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as CoinIdRouteImport } from './routes/coin.$id'
import { Route as MHandleRouteImport } from './routes/m.$handle'
import { Route as WalletIndexRouteImport } from './routes/wallet.index'
import { Route as WalletAddressRouteImport } from './routes/wallet.$address'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const LaunchRoute = LaunchRouteImport.update({
  id: '/launch',
  path: '/launch',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RoundsRoute = RoundsRouteImport.update({
  id: '/rounds',
  path: '/rounds',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const CoinIdRoute = CoinIdRouteImport.update({
  id: '/coin/$id',
  path: '/coin/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MHandleRoute = MHandleRouteImport.update({
  id: '/m/$handle',
  path: '/m/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletIndexRoute = WalletIndexRouteImport.update({
  id: '/wallet/',
  path: '/wallet/',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletAddressRoute = WalletAddressRouteImport.update({
  id: '/wallet/$address',
  path: '/wallet/$address',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/discover': typeof DiscoverRoute
  '/docs': typeof DocsRoute
  '/launch': typeof LaunchRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/rounds': typeof RoundsRoute
  '/status': typeof StatusRoute
  '/terms': typeof TermsRoute
  '/coin/$id': typeof CoinIdRoute
  '/m/$handle': typeof MHandleRoute
  '/wallet/$address': typeof WalletAddressRoute
  '/wallet/': typeof WalletIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/discover': typeof DiscoverRoute
  '/docs': typeof DocsRoute
  '/launch': typeof LaunchRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/rounds': typeof RoundsRoute
  '/status': typeof StatusRoute
  '/terms': typeof TermsRoute
  '/coin/$id': typeof CoinIdRoute
  '/m/$handle': typeof MHandleRoute
  '/wallet/$address': typeof WalletAddressRoute
  '/wallet': typeof WalletIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/discover': typeof DiscoverRoute
  '/docs': typeof DocsRoute
  '/launch': typeof LaunchRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/rounds': typeof RoundsRoute
  '/status': typeof StatusRoute
  '/terms': typeof TermsRoute
  '/coin/$id': typeof CoinIdRoute
  '/m/$handle': typeof MHandleRoute
  '/wallet/$address': typeof WalletAddressRoute
  '/wallet/': typeof WalletIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/discover'
    | '/docs'
    | '/launch'
    | '/privacy'
    | '/profile'
    | '/rounds'
    | '/status'
    | '/terms'
    | '/coin/$id'
    | '/m/$handle'
    | '/wallet/$address'
    | '/wallet/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/discover'
    | '/docs'
    | '/launch'
    | '/privacy'
    | '/profile'
    | '/rounds'
    | '/status'
    | '/terms'
    | '/coin/$id'
    | '/m/$handle'
    | '/wallet/$address'
    | '/wallet'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/discover'
    | '/docs'
    | '/launch'
    | '/privacy'
    | '/profile'
    | '/rounds'
    | '/status'
    | '/terms'
    | '/coin/$id'
    | '/m/$handle'
    | '/wallet/$address'
    | '/wallet/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  DiscoverRoute: typeof DiscoverRoute
  DocsRoute: typeof DocsRoute
  LaunchRoute: typeof LaunchRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  RoundsRoute: typeof RoundsRoute
  StatusRoute: typeof StatusRoute
  TermsRoute: typeof TermsRoute
  CoinIdRoute: typeof CoinIdRoute
  MHandleRoute: typeof MHandleRoute
  WalletAddressRoute: typeof WalletAddressRoute
  WalletIndexRoute: typeof WalletIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/launch': {
      id: '/launch'
      path: '/launch'
      fullPath: '/launch'
      preLoaderRoute: typeof LaunchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rounds': {
      id: '/rounds'
      path: '/rounds'
      fullPath: '/rounds'
      preLoaderRoute: typeof RoundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coin/$id': {
      id: '/coin/$id'
      path: '/coin/$id'
      fullPath: '/coin/$id'
      preLoaderRoute: typeof CoinIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m/$handle': {
      id: '/m/$handle'
      path: '/m/$handle'
      fullPath: '/m/$handle'
      preLoaderRoute: typeof MHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet/': {
      id: '/wallet/'
      path: '/wallet'
      fullPath: '/wallet/'
      preLoaderRoute: typeof WalletIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet/$address': {
      id: '/wallet/$address'
      path: '/wallet/$address'
      fullPath: '/wallet/$address'
      preLoaderRoute: typeof WalletAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  DiscoverRoute: DiscoverRoute,
  DocsRoute: DocsRoute,
  LaunchRoute: LaunchRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  RoundsRoute: RoundsRoute,
  StatusRoute: StatusRoute,
  TermsRoute: TermsRoute,
  CoinIdRoute: CoinIdRoute,
  MHandleRoute: MHandleRoute,
  WalletAddressRoute: WalletAddressRoute,
  WalletIndexRoute: WalletIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
